Desktop version
Vishal30M/Portfolio pull request #7
Opened 2023-04-07 21:42 UTC by Vishal30M

In this branch I did:
Edit index.html 
Add nav menu
Edit style.css
Give a responsive style to the website
Check for linter errors.

2023-04-07 22:39 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Vishal30M , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

## Highlights
- Nice Design :heavy_check_mark:
- The mobile design looks good :heavy_check_mark:
- Professional README :heavy_check_mark:
- No linter errors :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Giving your navbar a fixed position in both desktop and mobile :100: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 22:39 UTC, NahnahAJ commented on index.html
>                      <li class="main">CANOPY</li>
- Great job so far @Vishal30M There are just a few changes we need to make and your project will be complete :+1: 
- [ ] Each of your cards is missing some styles as seen in the Figma design. As a result, they don't look exactly like the Figma design. I have pointed them out in the image below so kindly fix these :wink: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/230685187-0c85cff8-0527-41dd-bc18-e372ddf73dfc.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/230685272-34aa3e78-b0a7-4679-96dd-688ccd376609.png)

2023-04-07 22:39 UTC, NahnahAJ commented on index.html
> +                            </a>
- [ ] Please ensure that the `about me` part takes 40% of the page and the `languages, skills and frameworks'` part takes the other 60% of the section as shown in the Figma Design :100: 

- [ ] There are also some other elements that need to be appropriately styled so your design looks similar to the Figma design. I have pointed them out in the image below :100: 

- Your Design
![image](https://user-images.githubusercontent.com/102699958/230686544-909f4457-d7b0-404b-a666-c82c08b54163.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/230458000-47622cf2-9c23-433a-b3ee-7b967202b742.png)

2023-04-08 09:06 UTC, Strangeal approved these changes
Hi @Vishal30M, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 09:14 UTC, merged